// <auto-generated />
namespace SellBook_Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateclothessss : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateclothessss));
        
        string IMigrationMetadata.Id
        {
            get { return "201806242257542_update-clothessss"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
