// <auto-generated />
namespace SellBook_Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateclothes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateclothes));
        
        string IMigrationMetadata.Id
        {
            get { return "201806241647383_update-clothes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
